language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
before_install:
  - sudo apt-get install cmake
  - chmod +x .ci/travis/*
  - .ci/travis/build_tests.sh
addons:
  apt:
    update: true
install:
  - pip install -r requirements.txt
script:
  - .ci/travis/run_tests.sh