dist: xenial
language: python
python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
before_install:
  - sudo apt-get install cmake
  - chmod +x .ci/travis/*
  - .ci/travis/build_tests.sh
addons:
  apt:
    update: true
install:
  - pip install pipenv
  - pipenv sync
script:
  - .ci/travis/run_tests.sh