language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
install:
  - pip install -r requirements.txt
script:
  - python contest.py examples//many_cases//contest_recipe.yaml
  - python contest.py examples//native_console_app//contest_recipe.yaml
  - python contest.py examples//output_file//contest_recipe.yaml
  - python contest.py examples//python_console_app//contest_recipe.yaml