name: Build

on: [push]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - run: |
        python -m pip install flake8
    - run: |
        flake8
  build-tests:
    needs: static-analysis
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Contest
      run: |
        python setup.py install
    - name: Build Tests
      run: |
        cd examples
        cmake .
        cmake --build . --target install
    - name: Tests
      run: |
        contest examples/many_cases/contest_recipe.yaml --verbose
        contest examples/native_console_app/contest_recipe.yaml --verbose
        # contest examples/output_file/contest_recipe.yaml --verbose
        contest examples/python_console_app/contest_recipe.yaml --verbose
  publish:
    needs: build-tests
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build Distribution
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.0.0a0
      with:
        user: __token__
        password: ${{ secrets.sneaky_contest }}
